apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eurmb0zk4-nodejs
  janus-idp.io/tekton: eurmb0zk4-nodejs
  backstage.io/kubernetes-id: eurmb0zk4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eurmb0zk4-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
